version: '3'
services:
  web:
    build: ./web
    ports:
      - "3000:3000"
    volumes:
      - ./web:/usr/src/app
    command: ["npm", "run", "dev"]
  api:
    build: ./api
    ports:
      - "8080:8080"
    volumes:
      - ./api:/usr/src/app
    command: ["mvn", "spring-boot:run"]
