spring:
    jpa:
        database: POSTGRESQL
        show-sql: true
        hibernate:
            ddl-auto: update
    datasource:
        url: jdbc:postgresql://db:5432/agile-harmony
        username: postgres
        password: example
        driverClassName: org.postgresql.Driver
